/*
* generated by Xtext
*/
package org.caltoopia.frontend.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.caltoopia.frontend.services.CalGrammarAccess;

public class CalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.caltoopia.frontend.parser.antlr.internal.InternalCalParser createParser(XtextTokenStream stream) {
		return new org.caltoopia.frontend.parser.antlr.internal.InternalCalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AstTop";
	}
	
	public CalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
