/*
 * generated by Xtext
 */
package org.caltoopia.frontend.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.caltoopia.frontend.ui.internal.CalActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CalActivator.getInstance().getInjector(CalActivator.ORG_CALTOOPIA_FRONTEND_CAL);
	}
	
}
