/*
 * generated by Xtext
 */
package org.caltoopia.frontend.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.caltoopia.frontend.ui.internal.CalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.caltoopia.frontend.ui.internal.CalActivator.getInstance().getInjector("org.caltoopia.frontend.Cal");
	}
	
}
